CREATE TABLE IF NOT EXISTS dev.dim_producto_hist_dev
(   _c0 VARCHAR(255)
    , fecha DATE
    , mes INTEGER
    , clave_temporada VARCHAR(255)
    , tiempo_ano_mes VARCHAR(255)
    , ano INTEGER
    , temporada VARCHAR(255)
    , status_compra VARCHAR(255)
    , sku VARCHAR(255)
    , sku_desc VARCHAR(255)
    , id_madre VARCHAR(255)
    , madre_desc VARCHAR(255)
    , nivel_1 VARCHAR(255)
    , nivel_2 VARCHAR(255)
    , nivel_3 VARCHAR(255)
    , nivel_4 VARCHAR(255)
    , grupo_analisis VARCHAR(255)
    , id_feria VARCHAR(255)
    , fob INTEGER
    , tipo_moneda VARCHAR(255)
    , pp INTEGER
    , moq INTEGER
    , tipo_moq VARCHAR(255)
    , cond_moq VARCHAR(255)
    , display VARCHAR(255)
    , pais_origen VARCHAR(255)
    , leadtime INTEGER
    , volumen INTEGER
    , peso INTEGER
    , inner_ INTEGER
    , master INTEGER
    , duracion VARCHAR(255)
    , fecha_ini DATE
    , fecha_ter DATE
    , fecha_ini_2 DATE
    , fecha_ter_2 DATE
    , num_material VARCHAR(255)
    , id_producto VARCHAR(255)
)
DISTKEY (id_producto) SORTKEY (fecha);