version: "3.7"

services:
  glue:
    image: glue-local:2
    depends_on:
      - s3
      - dynamodb-local
    build:
      context: .
      dockerfile: glue.dockerfile
    environment:
      AWS_ACCESS_KEY_ID: foobar
      AWS_SECRET_ACCESS_KEY: foobarfoo
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region us-east-1
  s3:
    hostname: s3
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    environment:
      MINIO_ACCESS_KEY: foobar
      MINIO_SECRET_KEY: foobarfoo
    ports:
      - "9000"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
