version: "3.7"

services:
  s3:
    hostname: s3
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - "9000"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data